# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - todo-web-app-service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      # Checkout the repo
      - uses: actions/checkout@v4

      # Set up Node.js
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Install dependencies and build React app
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      # Upload build folder as artifact
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app   # Artifact name
          path: build      # Upload build folder

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      # Download artifact
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app   # Download same artifact

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F865C2B6021B4AE295961FD3341C8F06 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F8DB45D81CED4BBBAC537A5D2E23EB87 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_273F12FF1973492EB3BFEF7B6A1C6CAD }}

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'todo-web-app-service'
          slot-name: 'Production'
          package: ./node-app   # Use downloaded artifact folder
